'use strict'

const {romanToArab, arabToRoman, isValidArab, isValidRoman} = require('../romanNumbers')

test('[romanToArab] Converts roman number to arab number', () => {
    expect(romanToArab('MMMCMXCIX')).toEqual(3999)
    expect(romanToArab('MMMC')).toEqual(3100)
    expect(romanToArab('CCLIV')).toEqual(254)
    expect(romanToArab('IX')).toEqual(9)
    expect(romanToArab('III')).toEqual(3)
    expect(romanToArab('QI')).toEqual(NaN)
    expect(romanToArab('i')).toEqual(NaN)
    expect(romanToArab('XM')).toEqual(NaN)
})

test('[arabToRoman] Converts arab number to roman number', () => {
    expect(arabToRoman(1)).toEqual('I')
    expect(arabToRoman(3999)).toEqual('MMMCMXCIX')
    expect(arabToRoman(990)).toEqual('CMXC')
    expect(arabToRoman(3100)).toEqual('MMMC')
    expect(arabToRoman(254)).toEqual('CCLIV')
    expect(arabToRoman(9)).toEqual('IX')
    expect(arabToRoman(3)).toEqual('III')
    expect(arabToRoman(0)).toEqual("")
    expect(arabToRoman(-1)).toEqual("")
    expect(arabToRoman(5.4)).toEqual("")
    expect(arabToRoman(4000)).toEqual("")
})

test('[isValidArab] Checks if arab number can be converted to roman', () => {
    expect(isValidArab(0)).toEqual(false)
    expect(isValidArab(1)).toEqual(true)
    expect(isValidArab(3999)).toEqual(true)
    expect(isValidArab(4000)).toEqual(false)
    expect(isValidArab(2.3)).toEqual(false)
    expect(isValidArab(-2)).toEqual(false)
    expect(isValidArab('X')).toEqual(false)
    expect(isValidArab('2')).toEqual(false)
    expect(isValidArab(false)).toEqual(false)
})

test('[isValidRoman] Checks if roman number can be converted to arab', () => {
    expect(isValidRoman('MMMCMXCIX')).toEqual(true)
    expect(isValidRoman('MMMCM')).toEqual(true)
    expect(isValidRoman('XIV')).toEqual(true)
    expect(isValidRoman('IIIX')).toEqual(false)
    expect(isValidRoman('')).toEqual(false)
    expect(isValidRoman('MMMCMM')).toEqual(false)
    expect(isValidRoman('MMMCMXCIXX')).toEqual(false)
    expect(isValidRoman('CMIVXCIXX')).toEqual(false)
    expect(isValidRoman('xiii')).toEqual(false)
    expect(isValidRoman('Xi')).toEqual(false)
    expect(isValidRoman('QA')).toEqual(false)
    expect(isValidRoman(2)).toEqual(false)
    expect(isValidRoman(false)).toEqual(false)
})
